error id: qQ2tbLxSa0b+nMJeQmO3Ig==
### Bloop error:

at scala.io.Source.hasNext(Source.scala:253)
#### Short summary: 

at scala.io.Source.hasNext(Source.scala:253)